### ISSUE TITLE
Updates in few section relate to social handles and contact information 

### ISSUE THREAD

**Issue by Riwajchalise** [RelevantResearch/michael-paarlberg#6]
![Screenshot 2024-09-15 at 11 47 04 PM](https://github.com/user-attachments/assets/3388723c-928b-4c2c-b0d9-a43642484300)
Please refere to the image or the readme file of this project in the base directory @SandeshNilasKhatiwada

**Comment by SandeshNilasKhatiwada** [comment]
## Solved Issue 6 
![Screenshot 2024-09-17 at 2 15 37 PM](https://github.com/user-attachments/assets/4bb11c3d-c410-4ddc-8eba-236b68404d5e)
created the profile section like this where he can show his cv and all the link to his social media account
